// Code generated by "stringer -type=sortOrder"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknown-0]
	_ = x[ascending-1]
	_ = x[descending-2]
}

const _sortOrder_name = "unknownascendingdescending"

var _sortOrder_index = [...]uint8{0, 7, 16, 26}

func (i sortOrder) String() string {
	if i < 0 || i >= sortOrder(len(_sortOrder_index)-1) {
		return "sortOrder(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sortOrder_name[_sortOrder_index[i]:_sortOrder_index[i+1]]
}
