name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # tag=v3
      with:
        go-version: '1.18'

    - name: Checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

    - name: Test with code coverage
      run: go test ./... -race -covermode=atomic -coverprofile=coverage.txt

    - name: Build binaries and Docker image with GoReleaser
      uses: goreleaser/goreleaser-action@b953231f81b8dfd023c58e0854a721e35037f28b # tag=v2
      with:
        args: release --snapshot --skip-publish

    - name: Run the built Docker image
      run: docker run ghcr.io/patrickhoefler/ghtop:0.0.0

  native:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # tag=v3
      with:
        go-version: '1.18'

    - name: Checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

    - name: Test
      run: go test ./...

    - name: Build
      run: go build

    - name: Run the binary
      run: ./ghtop
